format_map={
    "Bool": "?",
    "SInt": "<i",
    "UInt": "<I",
    "Real": "<f",
}

type_dict={

}

offset_map=[
{"address":0,"name":"xAlive","type":"Bool"},
{"address":1,"name":"xRemote","type":"Bool"},
{"address":2,"name":"xReserve1","type":"Bool"},
{"address":3,"name":"xReserve2","type":"Bool"},
{"address":4,"name":"xReserve3","type":"Bool"},
{"address":5,"name":"xReserve4","type":"Bool"},
{"address":6,"name":"xReserve5","type":"Bool"},
{"address":7,"name":"xReserve6","type":"Bool"},
{"address":8,"name":"xReserve7","type":"SInt"},
{"address":16,"name":"uiTelegramNo","type":"UInt"},
{"address":32,"name":"uiReserve1","type":"UInt"},
{"address":48,"name":"rReserve2","type":"Real"},
{"address":80,"name":"rReserve3","type":"Real"},
{"address":112,"name":"rReserve4","type":"Real"},
{"address":144,"name":"rReserve5","type":"Real"},
{"address":176,"name":"rReserve6","type":"Real"},
{"address":208,"name":"rReserve7","type":"Real"},
{"address":240,"name":"xMessungEin","type":"Bool"},
{"address":241,"name":"xRegelungEin","type":"Bool"},
{"address":242,"name":"xQuerRegEin","type":"Bool"},
{"address":243,"name":"xLaengsRegEin","type":"Bool"},
{"address":244,"name":"xKalibrierungEin","type":"Bool"},
{"address":245,"name":"xLinienmessungEin","type":"Bool"},
{"address":246,"name":"xReserve1","type":"Bool"},
{"address":247,"name":"xReserve2","type":"Bool"},
{"address":248,"name":"xReserve3","type":"SInt"},
{"address":256,"name":"xAL_1","type":"BInt"},
{"address":272,"name":"xAL_2","type":"BInt"},
{"address":288,"name":"rAktPos_Sensor","type":"Real"},
{"address":320,"name":"rAktDicke","type":"Real"},
{"address":352,"name":"rMittlereDicke","type":"Real"},
{"address":384,"name":"r2Sigma","type":"Real"},
{"address":416,"name":"rMaxDicke","type":"Real"},
{"address":448,"name":"rMinDicke","type":"Real"},
{"address":480,"name":"rSollDicke","type":"Real"},
{"address":512,"name":"rTolPos","type":"Real"},
{"address":544,"name":"rTolNeg","type":"Real"},
{"address":576,"name":"rMessung_StartPos","type":"Real"},
{"address":608,"name":"rMessung_EndPos","type":"Real"},
{"address":640,"name":"rNettoBreite","type":"Real"},
{"address":672,"name":"rNettoBreite_Start","type":"Real"},
{"address":704,"name":"rNettoBreite_End","type":"Real"},
{"address":736,"name":"rBruttoBreite","type":"Real"},
{"address":768,"name":"rBruttoBreite_Start","type":"Real"},
{"address":800,"name":"rBruttoBreite_End","type":"Real"},
{"address":832,"name":"rKalibrierungswert","type":"Real"},
{"address":864,"name":"rDicke_Corrwert","type":"Real"},
{"address":896,"name":"rKalibrierungspos","type":"Real"},
{"address":928,"name":"rSollzeit_Linienmessung","type":"Real"},
{"address":960,"name":"rPos_Linienmessung","type":"Real"},

]
    

